### ISSUE TITLE
http://ls2.fsbn.eu/live/

### ISSUE THREAD

**Issue by ridleywright** [wiiaboo/livestreaman#1]
Hey there. O Mega disse para mandar issue.

http://ls2.fsbn.eu/live/ não funciona. Isto não acontece acedendo ao http://ls2.fsbn.eu/index.php.
De qualquer forma, no utils.php, linha 20, mudaria para

if( (string) $streamer->name !== '' && self::isLive( $streamer ) ){

para garantir que o streamer escolhido tem nome atribuído. Não posso testar porque não consigo replicar o erro offline.

**Comment by wiiaboo** [comment]
Ya, tinha redirect permanente antes do `/` para `/live` (https://github.com/wiiaboo/livestreaman/blob/master/ls.fsbn.eu.conf#L9) e era por isso que antes aparecia um nome em branco.
Agora é preciso ir à history e fazer "Forget this site" para deixar de fazer o redirect, acho.
Alternativa é mudar o subdomain para outro e assim já não faz os redirects.

**Comment by wiiaboo** [comment]
Fora isso, só falta actualizar as bolinhas em tempo real ou perto, meter de volta os links para se poder ver em tablets e um pa fazer popout.

**Comment by ridleywright** [comment]
Urgh ya, não me lembrei que podia ser da cache. Derpderp.

Os links que estás a falar eram os que apareciam abaixo do stream na versão antiga não? E o de rádio para o teu (?) stream, amirite?

**Comment by wiiaboo** [comment]
Esse era só por conveniência minha. Raramente a ligo. Não é preciso código só para isso.

**Comment by ridleywright** [comment]
Os outros dois então. E o live em tempo real. Got it. Ver se faço isso até sexta praí.

**Comment by wiiaboo** [comment]
np, sem pressas

**Comment by Agleal** [comment]
Bandalhos, ambos.

**Comment by wiiaboo** [comment]
ui, tens conta no github, também és brogrammer?

**Comment by wiiaboo** [comment]
Maior parte dos fixes é por causa de pequenas coisas na interecção com o nginx.
Já meti os links temporariamente porque o relíquias tem portátil com resolução cocó.
